### PR TITLE
updates to german translations

### PR DESCRIPTION
**Pull request by ildorn**
better german translations. with comments for other possible translations and reasons for some of them.

### CODE REVIEW

**Comment by Vostro162** [comment]
I see my translation i will improve my translation for the next release. But which german You want standart german or Business german ?

**Comment by mandel-macaque** [comment]
Good question, I've used standard spanish and english, so use whatver you refer. @ildorn I'll update the transations using the strings you provided and will do another release.

Doing releases is "cheap" so do not worry too much :)

**Comment by ildorn** [comment]
Should work now. I think I didn't use any business german...

**Comment by Vostro162** [comment]
okay doesn't matter ^^ i checkout the new release for bugs :D

**Comment by mandel-macaque** [comment]
@ildorn perfect, will do a small release with the fix.

**Comment by mandel-macaque** [comment]
Version 0.17 should have the fixes. Thx for the help!!!!!

**Pull request merged**
